version: "3.7"

services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: goodreads
      POSTGRES_PASSWORD: goodreads
      POSTGRES_USER: goodreads
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - ./data:/data